version: "3.9"

services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  users-service:
    build: ./services/users-service
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/users
    depends_on:
      - mongo

  orders-service:
    build: ./services/orders-service
    ports:
      - "8001:8001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/orders
    depends_on:
      - mongo
      - users-service

  payments-service:
    build: ./services/payments-service
    ports:
      - "8002:8002"
    environment:
      - MONGO_URI=mongodb://mongo:27017/payments
    depends_on:
      - mongo
      - orders-service

volumes:
  mongo_data:
